// lang.js — Internationalization module
// Exposes: PicAnalysis.Lang

var PicAnalysis = PicAnalysis || {};

PicAnalysis.Lang = (function () {
  var currentLang = "zh";
  var listeners = [];

  var translations = {
    en: {
      appTitle: "ToneLab",
      resetParams: "Reset Params",
      uploadNew: "Upload New",
      download: "Download",
      modePhoto: "Photo",
      modeIllustration: "Illust.",
      dropText: "Drop image here or click to upload",
      dropHint: "Supports JPG, PNG, WebP",
      introTitle: "Smart Image Analysis & Adjustment Tool",
      introDesc: "Upload an image and the system will automatically analyze brightness, contrast, saturation, color temperature, and more. It detects scene styles (e.g. low-key, golden hour, portrait) and suggests adjustments accordingly. You can fine-tune all parameters in real time and compare before/after results.",
      introF1Title: "Auto Diagnosis",
      introF1Desc: "Analyzes 10+ metrics including brightness, color, and contrast",
      introF2Title: "Scene Detection",
      introF2Desc: "Identifies 14 scene styles and adapts strategy to preserve artistic intent",
      introF3Title: "Full Control",
      introF3Desc: "32 tunable parameters, 5 preset slots, Photo & Illustration dual modes",
      processing: "PROCESSING...",
      original: "Original",
      adjusted: "Adjusted",
      diagnosis: "Diagnosis",
      diagOriginal: "Original",
      diagAdjusted: "Adjusted",
      activeAdjustments: "Active Adjustments",
      parameters: "Parameters",

      // Histogram labels
      lum: "Lum",

      // Diagnosis
      brightnessMean: "Brightness Mean",
      contrastStd: "Contrast (Std)",
      skewness: "Skewness",
      dynamicRange: "Dynamic Range",
      saturationMean: "Saturation Mean",
      colorTempBias: "Color Temp Bias",
      tintBias: "Tint Bias (G/M)",
      dominantColors: "Dominant Colors",
      colorHarmony: "Color Harmony",
      regionAnalysis: "Regional Analysis",
      regionContrast: "Region Contrast",
      centerEdgeDiff: "Center-Edge Diff",
      darkestRegion: "Darkest",
      brightestRegion: "Brightest",

      // Region position labels
      "pos.TL": "Top-Left", "pos.TC": "Top-Center", "pos.TR": "Top-Right",
      "pos.ML": "Mid-Left", "pos.MC": "Center", "pos.MR": "Mid-Right",
      "pos.BL": "Bot-Left", "pos.BC": "Bot-Center", "pos.BR": "Bot-Right",

      // Harmony types
      "harmony.neutral": "Neutral (Achromatic)",
      "harmony.monochromatic": "Monochromatic",
      "harmony.analogous": "Analogous",
      "harmony.complementary": "Complementary",
      "harmony.splitComplementary": "Split-Complementary",
      "harmony.triadic": "Triadic",
      "harmony.tetradic": "Tetradic (Square)",
      "harmony.diverse": "Diverse",

      // Presets
      presets: "Presets",
      presetSave: "Save",
      presetLoad: "Load",
      presetDelete: "Delete",
      presetEmpty: "Empty",
      presetNamePrompt: "Enter preset name:",
      presetOverwrite: "Overwrite existing preset?",

      // Control sections
      strategyThresholds: "Strategy Thresholds",
      targetValues: "Target Values",
      adjustmentStrengths: "Adjustment Strengths",

      // Control labels
      brightnessSkewThreshold: "Brightness Skew Threshold",
      minDynamicRange: "Min Dynamic Range",
      maxContrastStd: "Max Contrast (Std)",
      minVibranceMean: "Vibrance Threshold",
      minSaturationMean: "Min Saturation Mean",
      maxSaturationMean: "Max Saturation Mean",
      maxColorTempBias: "Max Color Temp Bias",
      maxTintBias: "Max Tint Bias",
      shadowP5Threshold: "Shadow P5 Threshold",
      highlightP95Threshold: "Highlight P95 Threshold",
      clarityMinMidtoneRange: "Clarity Midtone Threshold",
      brightnessTarget: "Brightness Target",
      contrastTargetRange: "Contrast Target Range",
      saturationTarget: "Saturation Target",
      globalStrength: "Global Strength",
      brightness: "Brightness",
      contrast: "Contrast",
      contrastReduction: "Contrast Reduction",
      vibrance: "Vibrance",
      saturation: "Saturation",
      desaturation: "Desaturation",
      whiteBalance: "White Balance",
      tintCorrection: "Tint Correction",
      shadowRecovery: "Shadow Recovery",
      highlightRecovery: "Highlight Recovery",
      clarity: "Clarity",

      // Slider tooltips
      "tip.brightnessSkewThreshold": "Left: triggers brightness correction on slight skew, more images get adjusted. Right: only corrects strongly skewed images, preserves original tone.",
      "tip.contrastMinDynamicRange": "Left: tolerates flat, low-contrast images. Right: demands wider tonal range, more images get contrast boost.",
      "tip.contrastMaxStd": "Left: tolerates high contrast, posterized look. Right: reduces contrast when std deviation exceeds this threshold.",
      "tip.vibranceMinMean": "Left: accepts muted colors without vibrance boost. Right: triggers smart saturation on more images — boosts dull areas while protecting skin tones and already-vivid colors.",
      "tip.saturationMinMean": "Left: accepts muted, desaturated palettes. Right: requires richer color, triggering saturation boost more often.",
      "tip.saturationMaxMean": "Left: reduces saturation earlier, preventing gaudy colors. Right: tolerates vivid, highly saturated images.",
      "tip.whiteBalanceMaxBias": "Left: corrects even slight warm/cool tints. Right: tolerates stronger color casts before correcting.",
      "tip.tintMaxBias": "Left: corrects even slight green/magenta tints. Right: tolerates stronger tint before correcting.",
      "tip.shadowP5Threshold": "Left: accepts crushed blacks, darker mood. Right: recovers more shadow detail, lifts dark areas.",
      "tip.highlightP95Threshold": "Left: pulls back highlights earlier, preserves more bright detail. Right: tolerates near-white areas, brighter output.",
      "tip.clarityMinMidtoneRange": "Left: tolerates flat midtones, softer look. Right: demands wider midtone separation, more images get clarity boost.",
      "tip.brightnessTarget": "Left: aims for a darker overall image. Right: aims for a brighter, lighter image.",
      "tip.contrastTarget": "Left: targets narrower tonal range, softer look. Right: targets wider range, punchier contrast.",
      "tip.saturationTarget": "Left: targets muted, understated colors. Right: targets vivid, vibrant colors.",
      "tip.globalStrength": "Left: minimal overall adjustment, closer to original. Right: stronger effect across all adjustments.",
      "tip.brightnessStrength": "Left: gentle brightness correction. Right: aggressive brightness shift.",
      "tip.contrastStrength": "Left: subtle contrast enhancement. Right: dramatic contrast boost.",
      "tip.contrastReductionStrength": "Left: gentle contrast softening. Right: strong contrast compression.",
      "tip.vibranceStrength": "Left: subtle vibrance boost. Right: strong smart saturation — still protects skin tones and already-saturated areas.",
      "tip.saturationStrength": "Left: mild saturation change. Right: intense color saturation.",
      "tip.desaturationStrength": "Left: gentle desaturation. Right: strong color muting.",
      "tip.whiteBalanceStrength": "Left: gentle white balance correction. Right: strong color temperature shift.",
      "tip.tintStrength": "Left: gentle tint correction. Right: strong green/magenta shift.",
      "tip.shadowStrength": "Left: subtle shadow lift. Right: aggressively brightens dark areas.",
      "tip.highlightStrength": "Left: gentle highlight recovery. Right: strongly pulls down bright areas.",
      "tip.clarityStrength": "Left: subtle midtone definition. Right: strong midtone punch — adds texture and depth without touching shadows or highlights.",

      // Scene awareness
      sceneAwareness: "Scene Awareness",
      "tip.sceneAwareness": "Left: ignore detected scenes, pure correction mode. Right: fully respect artistic intent, suppress conflicting adjustments.",
      detectedScenes: "Detected Scenes",
      sceneSuppressedBy: "suppressed by {scene}",
      noScenesDetected: "No artistic scenes detected",
      "scene.lowKey": "Low-Key",
      "scene.highKey": "High-Key",
      "scene.desaturated": "Desaturated",
      "scene.colorAccent": "Color Accent",
      "scene.warmTone": "Warm Tone",
      "scene.coolTone": "Cool Tone",
      "scene.highContrast": "High Contrast",
      "scene.silhouette": "Silhouette",
      "scene.softDreamy": "Soft / Dreamy",
      "scene.foggy": "Foggy / Hazy",
      "scene.goldenHour": "Golden Hour",
      "scene.pastel": "Pastel",
      "scene.neon": "Neon / Cyberpunk",
      "scene.portrait": "Portrait",
      "sceneDesc.lowKey": "Intentional dark mood detected — brightness boost and shadow recovery suppressed",
      "sceneDesc.highKey": "Intentional bright style detected — darkening and highlight recovery suppressed",
      "sceneDesc.desaturated": "Intentional muted palette detected — saturation boost suppressed",
      "sceneDesc.colorAccent": "Muted palette with vivid color accent — saturation and desaturation suppressed to preserve the pop",
      "sceneDesc.warmTone": "Intentional warm cast detected — cool white balance correction suppressed",
      "sceneDesc.coolTone": "Intentional cool cast detected — warm white balance correction suppressed",
      "sceneDesc.highContrast": "Intentional strong contrast detected — contrast boost and tonal recovery suppressed",
      "sceneDesc.silhouette": "Silhouette composition detected — most auto-adjustments suppressed",
      "sceneDesc.softDreamy": "Soft dreamy style detected — contrast boost and highlight recovery suppressed",
      "sceneDesc.foggy": "Foggy/hazy atmosphere detected — contrast, saturation, and shadow recovery suppressed",
      "sceneDesc.goldenHour": "Golden hour warmth detected — white balance and tint correction strongly suppressed",
      "sceneDesc.pastel": "Pastel palette detected — contrast and desaturation suppressed to preserve soft candy tones",
      "sceneDesc.neon": "Neon/cyberpunk palette detected — desaturation and white balance correction suppressed to preserve vivid cool tones",
      "sceneDesc.portrait": "Portrait with skin tones detected — saturation, vibrance, contrast, and white balance suppressed",
      sceneFactors: "Detection Factors",
      scenePopupClose: "Click anywhere to close",
      "factor.darkMean": "Low brightness",
      "factor.darkSkew": "Dark pixel mass",
      "factor.hasRange": "Dynamic range",
      "factor.deepBlacks": "Deep blacks",
      "factor.brightMean": "High brightness",
      "factor.brightSkew": "Bright pixel mass",
      "factor.brightHighlights": "Bright highlights",
      "factor.lowSatMean": "Low saturation",
      "factor.lowSatStd": "Uniform saturation",
      "factor.lowDominantSat": "Muted dominants",
      "factor.lowOverallSat": "Low overall saturation",
      "factor.vividAccent": "Vivid accent cluster",
      "factor.accentMinority": "Accent is minority",
      "factor.satVariance": "Saturation variance",
      "factor.warmBias": "Warm color bias",
      "factor.warmDominant": "Warm hue dominance",
      "factor.warmConsistency": "Global consistency",
      "factor.coolBias": "Cool color bias",
      "factor.coolDominant": "Cool hue dominance",
      "factor.coolConsistency": "Global consistency",
      "factor.highStd": "High luminance spread",
      "factor.highRange": "Wide dynamic range",
      "factor.bimodal": "Bimodal histogram",
      "factor.extremeRange": "Extreme range",
      "factor.regionGap": "Region contrast gap",
      "factor.lowContrast": "Low contrast",
      "factor.brightOverall": "Overall brightness",
      "factor.narrowRange": "Narrow range",
      "factor.softSat": "Soft saturation",
      "factor.liftedShadows": "Lifted shadows",
      "factor.lowSat": "Low saturation",
      "factor.uniformRegions": "Uniform regions",
      "factor.strongWarm": "Strong warm cast",
      "factor.richSat": "Rich saturation",
      "factor.vividDominants": "Vivid dominants",
      "factor.moderateSat": "Moderate saturation",
      "factor.hueDiversity": "Hue diversity",
      "factor.highSat": "High saturation",
      "factor.highContrast": "High contrast",
      "factor.neonHues": "Neon hue dominance",
      "factor.skinHues": "Skin tone hues",
      "factor.skinSat": "Skin saturation",
      "factor.centerBrighter": "Center brighter",
      "factor.moderateContrast": "Moderate contrast",

      // Adjustment type display names
      "type.brightness": "Brightness",
      "type.contrast": "Contrast",
      "type.contrastReduction": "Contrast Reduction",
      "type.vibrance": "Vibrance",
      "type.saturation": "Saturation",
      "type.desaturation": "Desaturation",
      "type.whiteBalance": "White Balance",
      "type.tintCorrection": "Tint Correction",
      "type.shadowRecovery": "Shadow Recovery",
      "type.highlightRecovery": "Highlight Recovery",
      "type.clarity": "Clarity",

      // Reason messages
      "reason.brightnessSkewsDark": "Image skews dark (skewness: {val})",
      "reason.brightnessSkewsBright": "Image skews bright (skewness: {val})",
      "reason.brightnessBalanced": "Brightness balanced (skewness: {val})",
      "reason.lowDynamicRange": "Low dynamic range ({val})",
      "reason.adequateContrast": "Adequate contrast (range: {val})",
      "reason.highContrast": "Over-contrast (std: {val})",
      "reason.contrastOk": "Contrast OK (std: {val})",
      "reason.lowVibranceSaturation": "Dull colors, vibrance needed (mean: {val})",
      "reason.adequateVibrance": "Vibrance adequate (mean: {val})",
      "reason.lowSaturation": "Low saturation (mean: {val})",
      "reason.adequateSaturation": "Adequate saturation (mean: {val})",
      "reason.highSaturation": "Over-saturated (mean: {val})",
      "reason.saturationOk": "Saturation OK (mean: {val})",
      "reason.warmBias": "Warm bias ({val})",
      "reason.coolBias": "Cool bias ({val})",
      "reason.balancedColorTemp": "Balanced color temp ({val})",
      "reason.greenTint": "Green tint ({val})",
      "reason.magentaTint": "Magenta tint ({val})",
      "reason.balancedTint": "Balanced tint ({val})",
      "reason.crushedShadows": "Crushed shadows (P5: {val})",
      "reason.shadowsOk": "Shadows OK (P5: {val})",
      "reason.blownHighlights": "Blown highlights (P95: {val})",
      "reason.highlightsOk": "Highlights OK (P95: {val})",
      "reason.flatMidtones": "Flat midtones (IQR: {val})",
      "reason.midtonesOk": "Midtone contrast OK (IQR: {val})",

      // Conflict resolution
      "conflict.contrastWins": "Disabled: contrast boost takes priority",
      "conflict.contrastReductionWins": "Disabled: contrast reduction takes priority",
      "conflict.saturationWins": "Disabled: saturation boost takes priority",
      "conflict.desaturationWins": "Disabled: desaturation takes priority",
      "conflict.vibranceOverlap": "Reduced 40%: vibrance already covers smart saturation",
      "conflict.brightnessOverlap": "Reduced 30%: brightness shift already affects this range",
      "conflict.harmonyGuard": "Reduced: structured color harmony detected, protecting palette balance",
      "conflict.contrastOverlap": "Reduced 40%: contrast boost already widens midtone range",
    },

    zh: {
      appTitle: "調色研究所",
      resetParams: "重設參數",
      uploadNew: "上傳新圖",
      download: "下載",
      modePhoto: "攝影",
      modeIllustration: "電繪",
      dropText: "拖放圖片至此處，或點擊上傳",
      dropHint: "支援 JPG、PNG、WebP",
      introTitle: "智慧圖片分析與調整工具",
      introDesc: "上傳一張圖片，系統會自動分析亮度、對比度、飽和度、色溫等特徵，偵測場景風格（如暗調、黃金時刻、人像等），並根據分析結果給出調整建議。你可以即時微調所有參數，比較原圖與調整後的效果。",
      introF1Title: "自動診斷",
      introF1Desc: "分析圖片的亮度、色彩、對比度等 10+ 項指標",
      introF2Title: "場景偵測",
      introF2Desc: "辨識 14 種場景風格，自動調整策略避免破壞藝術意圖",
      introF3Title: "完整控制",
      introF3Desc: "32 項可調參數，5 組預設儲存，攝影與電繪雙模式",
      processing: "處理中...",
      original: "原圖",
      adjusted: "調整後",
      diagnosis: "診斷結果",
      diagOriginal: "原圖",
      diagAdjusted: "調整後",
      activeAdjustments: "啟用的調整項目",
      parameters: "參數設定",

      lum: "亮度",

      brightnessMean: "平均亮度",
      contrastStd: "對比度 (標準差)",
      skewness: "偏態",
      dynamicRange: "動態範圍",
      saturationMean: "平均飽和度",
      colorTempBias: "色溫偏移",
      tintBias: "色調偏移 (G/M)",
      dominantColors: "主色調",
      colorHarmony: "色彩和諧",
      regionAnalysis: "區域分析",
      regionContrast: "區域對比",
      centerEdgeDiff: "中心-邊緣差",
      darkestRegion: "最暗區域",
      brightestRegion: "最亮區域",

      "pos.TL": "左上", "pos.TC": "上中", "pos.TR": "右上",
      "pos.ML": "左中", "pos.MC": "中心", "pos.MR": "右中",
      "pos.BL": "左下", "pos.BC": "下中", "pos.BR": "右下",

      "harmony.neutral": "中性（消色）",
      "harmony.monochromatic": "單色系",
      "harmony.analogous": "類比色",
      "harmony.complementary": "互補色",
      "harmony.splitComplementary": "分裂互補",
      "harmony.triadic": "三角配色",
      "harmony.tetradic": "四角配色",
      "harmony.diverse": "多元配色",

      presets: "預設組合",
      presetSave: "儲存",
      presetLoad: "載入",
      presetDelete: "清除",
      presetEmpty: "空白",
      presetNamePrompt: "輸入預設名稱：",
      presetOverwrite: "是否覆蓋現有的預設？",

      strategyThresholds: "策略閾值",
      targetValues: "目標值",
      adjustmentStrengths: "調整強度",

      brightnessSkewThreshold: "亮度偏態閾值",
      minDynamicRange: "最低動態範圍",
      maxContrastStd: "最大對比度（標準差）",
      minVibranceMean: "自然飽和度閾值",
      minSaturationMean: "最低平均飽和度",
      maxSaturationMean: "最高平均飽和度",
      maxColorTempBias: "最大色溫偏移",
      maxTintBias: "最大色調偏移",
      shadowP5Threshold: "暗部 P5 閾值",
      highlightP95Threshold: "亮部 P95 閾值",
      clarityMinMidtoneRange: "清晰度中間調閾值",
      brightnessTarget: "亮度目標值",
      contrastTargetRange: "對比度目標範圍",
      saturationTarget: "飽和度目標值",
      globalStrength: "整體強度",
      brightness: "亮度",
      contrast: "對比度",
      contrastReduction: "對比度降低",
      vibrance: "自然飽和度",
      saturation: "飽和度",
      desaturation: "去飽和",
      whiteBalance: "白平衡",
      tintCorrection: "色調校正",
      shadowRecovery: "暗部恢復",
      highlightRecovery: "亮部恢復",
      clarity: "清晰度",

      "tip.brightnessSkewThreshold": "往左：輕微偏態就觸發亮度修正，更多圖片會被調整。往右：僅修正嚴重偏態的圖片，保留原始色調。",
      "tip.contrastMinDynamicRange": "往左：容許平淡低對比的畫面。往右：要求更寬的色調範圍，更多圖片會被增強對比。",
      "tip.contrastMaxStd": "往左：容許高對比度、色調分離效果。往右：當標準差超過此閾值時降低對比度。",
      "tip.vibranceMinMean": "往左：接受色彩平淡而不啟用自然飽和度。往右：更多圖片會觸發智慧飽和度提升——增強暗淡區域同時保護膚色與已鮮豔的色彩。",
      "tip.saturationMinMean": "往左：接受柔和、低飽和的色彩。往右：要求更豐富的色彩，更頻繁地提升飽和度。",
      "tip.saturationMaxMean": "往左：更早降低飽和度，避免俗豔。往右：容許鮮豔高飽和的畫面。",
      "tip.whiteBalanceMaxBias": "往左：即使輕微偏暖偏冷也會修正。往右：容許較強的色偏才進行校正。",
      "tip.tintMaxBias": "往左：即使輕微偏綠偏洋紅也會修正。往右：容許較強的色調偏移才進行校正。",
      "tip.shadowP5Threshold": "往左：接受暗沉的黑色，保留深沉氛圍。往右：恢復更多暗部細節，提亮陰影區域。",
      "tip.highlightP95Threshold": "往左：更早拉回高光，保留更多亮部細節。往右：容許接近純白的區域，畫面更明亮。",
      "tip.clarityMinMidtoneRange": "往左：容許平淡的中間調，柔和感。往右：要求更寬的中間調分離，更多圖片會獲得清晰度提升。",
      "tip.brightnessTarget": "往左：目標偏暗的整體畫面。往右：目標更明亮、更輕盈的畫面。",
      "tip.contrastTarget": "往左：目標較窄的色調範圍，柔和感。往右：目標更寬的範圍，更有衝擊力的對比。",
      "tip.saturationTarget": "往左：目標低調內斂的色彩。往右：目標鮮豔飽滿的色彩。",
      "tip.globalStrength": "往左：整體調整力度最小，接近原圖。往右：所有調整效果更強烈。",
      "tip.brightnessStrength": "往左：溫和的亮度修正。往右：大幅度的亮度偏移。",
      "tip.contrastStrength": "往左：細微的對比增強。往右：戲劇性的對比提升。",
      "tip.contrastReductionStrength": "往左：溫和的對比度柔化。往右：大幅度的對比度壓縮。",
      "tip.vibranceStrength": "往左：細微的自然飽和度提升。往右：強烈的智慧飽和——仍然保護膚色與已飽和的區域。",
      "tip.saturationStrength": "往左：輕微的飽和度變化。往右：強烈的色彩飽和。",
      "tip.desaturationStrength": "往左：輕微的去飽和。往右：大幅度去除飽和度。",
      "tip.whiteBalanceStrength": "往左：溫和的白平衡校正。往右：大幅度的色溫偏移。",
      "tip.tintStrength": "往左：溫和的色調校正。往右：大幅度的綠/洋紅偏移。",
      "tip.shadowStrength": "往左：細微的暗部提亮。往右：大幅度提亮陰影區域。",
      "tip.highlightStrength": "往左：溫和的高光恢復。往右：強力壓低明亮區域。",
      "tip.clarityStrength": "往左：細微的中間調層次。往右：強烈的中間調質感——增添紋理與深度，不碰暗部和亮部。",

      // Scene awareness
      sceneAwareness: "場景感知",
      "tip.sceneAwareness": "往左：忽略場景偵測，純糾偏模式。往右：完全尊重藝術意圖，抑制衝突的調整。",
      detectedScenes: "偵測到的場景風格",
      sceneSuppressedBy: "因{scene}場景已抑制",
      noScenesDetected: "未偵測到特定藝術場景",
      "scene.lowKey": "暗調",
      "scene.highKey": "亮調",
      "scene.desaturated": "消色系",
      "scene.colorAccent": "點綴色",
      "scene.warmTone": "暖調",
      "scene.coolTone": "冷調",
      "scene.highContrast": "高對比",
      "scene.silhouette": "剪影",
      "scene.softDreamy": "柔焦夢幻",
      "scene.foggy": "霧氣朦朧",
      "scene.goldenHour": "黃金時刻",
      "scene.pastel": "粉彩",
      "scene.neon": "霓虹賽博",
      "scene.portrait": "人像",
      "sceneDesc.lowKey": "偵測到刻意的暗調氛圍，已減少提亮和暗部恢復",
      "sceneDesc.highKey": "偵測到刻意的亮調風格，已減少壓暗和高光恢復",
      "sceneDesc.desaturated": "偵測到刻意的低飽和風格，已減少飽和度提升",
      "sceneDesc.colorAccent": "偵測到低飽和畫面中的鮮豔點綴色，已抑制飽和度與去飽和調整以保護色彩對比",
      "sceneDesc.warmTone": "偵測到刻意的暖色調，已減少白平衡冷色修正",
      "sceneDesc.coolTone": "偵測到刻意的冷色調，已減少白平衡暖色修正",
      "sceneDesc.highContrast": "偵測到刻意的高對比風格，已減少對比度和暗部/亮部調整",
      "sceneDesc.silhouette": "偵測到剪影構圖，已大幅減少各項自動調整",
      "sceneDesc.softDreamy": "偵測到柔焦夢幻風格，已減少對比度和高光恢復",
      "sceneDesc.foggy": "偵測到霧氣朦朧氛圍，已減少對比度、飽和度和暗部恢復",
      "sceneDesc.goldenHour": "偵測到黃金時刻暖色調，已大幅減少白平衡和色調校正",
      "sceneDesc.pastel": "偵測到粉彩色調，已減少對比度和去飽和以保護柔和糖果色",
      "sceneDesc.neon": "偵測到霓虹賽博色調，已抑制去飽和與白平衡修正以保護鮮豔冷色調",
      "sceneDesc.portrait": "偵測到含膚色的人像，已減少飽和度、自然飽和度、對比度和白平衡",
      sceneFactors: "判定依據",
      scenePopupClose: "點擊任意處關閉",
      "factor.darkMean": "低亮度",
      "factor.darkSkew": "暗像素集中",
      "factor.hasRange": "動態範圍",
      "factor.deepBlacks": "深黑色",
      "factor.brightMean": "高亮度",
      "factor.brightSkew": "亮像素集中",
      "factor.brightHighlights": "明亮高光",
      "factor.lowSatMean": "低飽和度",
      "factor.lowSatStd": "飽和度均勻",
      "factor.lowDominantSat": "主色消色",
      "factor.lowOverallSat": "整體低飽和",
      "factor.vividAccent": "鮮豔點綴色群",
      "factor.accentMinority": "點綴色佔少數",
      "factor.satVariance": "飽和度差異大",
      "factor.warmBias": "暖色偏移",
      "factor.warmDominant": "暖色相佔比",
      "factor.warmConsistency": "全局一致性",
      "factor.coolBias": "冷色偏移",
      "factor.coolDominant": "冷色相佔比",
      "factor.coolConsistency": "全局一致性",
      "factor.highStd": "亮度分散高",
      "factor.highRange": "寬動態範圍",
      "factor.bimodal": "雙峰直方圖",
      "factor.extremeRange": "極端範圍",
      "factor.regionGap": "區域對比差",
      "factor.lowContrast": "低對比度",
      "factor.brightOverall": "整體明亮",
      "factor.narrowRange": "窄動態範圍",
      "factor.softSat": "柔和飽和度",
      "factor.liftedShadows": "暗部提升",
      "factor.lowSat": "低飽和度",
      "factor.uniformRegions": "區域均勻",
      "factor.strongWarm": "強暖色調",
      "factor.richSat": "飽和度豐富",
      "factor.vividDominants": "鮮豔主色",
      "factor.moderateSat": "適中飽和度",
      "factor.hueDiversity": "色相多樣性",
      "factor.highSat": "高飽和度",
      "factor.highContrast": "高對比度",
      "factor.neonHues": "霓虹色相佔比",
      "factor.skinHues": "膚色色相",
      "factor.skinSat": "膚色飽和度",
      "factor.centerBrighter": "中心較亮",
      "factor.moderateContrast": "適中對比度",

      "type.brightness": "亮度",
      "type.contrast": "對比度",
      "type.contrastReduction": "對比度降低",
      "type.vibrance": "自然飽和度",
      "type.saturation": "飽和度",
      "type.desaturation": "去飽和",
      "type.whiteBalance": "白平衡",
      "type.tintCorrection": "色調校正",
      "type.shadowRecovery": "暗部恢復",
      "type.highlightRecovery": "亮部恢復",
      "type.clarity": "清晰度",

      "reason.brightnessSkewsDark": "圖片偏暗（偏態：{val}）",
      "reason.brightnessSkewsBright": "圖片偏亮（偏態：{val}）",
      "reason.brightnessBalanced": "亮度均衡（偏態：{val}）",
      "reason.lowDynamicRange": "動態範圍不足（{val}）",
      "reason.adequateContrast": "對比度充足（範圍：{val}）",
      "reason.highContrast": "對比度過高（標準差：{val}）",
      "reason.contrastOk": "對比度正常（標準差：{val}）",
      "reason.lowVibranceSaturation": "色彩暗淡，需要自然飽和度提升（均值：{val}）",
      "reason.adequateVibrance": "自然飽和度充足（均值：{val}）",
      "reason.lowSaturation": "飽和度偏低（均值：{val}）",
      "reason.adequateSaturation": "飽和度充足（均值：{val}）",
      "reason.highSaturation": "飽和度過高（均值：{val}）",
      "reason.saturationOk": "飽和度正常（均值：{val}）",
      "reason.warmBias": "偏暖（{val}）",
      "reason.coolBias": "偏冷（{val}）",
      "reason.balancedColorTemp": "色溫平衡（{val}）",
      "reason.greenTint": "偏綠（{val}）",
      "reason.magentaTint": "偏洋紅（{val}）",
      "reason.balancedTint": "色調平衡（{val}）",
      "reason.crushedShadows": "暗部細節不足（P5：{val}）",
      "reason.shadowsOk": "暗部正常（P5：{val}）",
      "reason.blownHighlights": "亮部過曝（P95：{val}）",
      "reason.highlightsOk": "亮部正常（P95：{val}）",
      "reason.flatMidtones": "中間調平淡（四分位距：{val}）",
      "reason.midtonesOk": "中間調對比正常（四分位距：{val}）",

      // Conflict resolution
      "conflict.contrastWins": "已停用：對比度增強優先",
      "conflict.contrastReductionWins": "已停用：對比度降低優先",
      "conflict.saturationWins": "已停用：飽和度增強優先",
      "conflict.desaturationWins": "已停用：去飽和優先",
      "conflict.vibranceOverlap": "已減少 40%：自然飽和度已涵蓋智慧飽和",
      "conflict.brightnessOverlap": "已減少 30%：亮度偏移已影響此範圍",
      "conflict.harmonyGuard": "已減少：偵測到結構化色彩和諧，保護配色平衡",
      "conflict.contrastOverlap": "已減少 40%：對比度增強已拓寬中間調範圍",
    },
  };

  function t(key, values) {
    var dict = translations[currentLang] || translations.en;
    var str = dict[key] || translations.en[key] || key;
    if (values) {
      for (var k in values) {
        str = str.replace("{" + k + "}", values[k]);
      }
    }
    return str;
  }

  function getLang() {
    return currentLang;
  }

  function setLang(lang) {
    if (lang === currentLang) return;
    currentLang = lang;
    for (var i = 0; i < listeners.length; i++) {
      listeners[i](currentLang);
    }
  }

  function onChange(fn) {
    listeners.push(fn);
  }

  return {
    t: t,
    getLang: getLang,
    setLang: setLang,
    onChange: onChange,
  };
})();
